version: '2.4'
services:
  web:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ./demo-web:/var/www/html
    networks:
      net:
        ipv4_address: 172.28.1.1
  modernization:
    image: modernization_server
    build: ./modernization
    ports:
      - "6542"
    volumes:
      - ./modernization/models:/opt/nmt-keras/models
      - ./modernization/config.py:/opt/nmt-keras/config.py
      - ./modernization/dataset:/opt/nmt-keras/dataset
      - ./modernization/config_online.py:/opt/nmt-keras/demo-web/config_online.py
    networks:
      net:
        ipv4_address: 172.28.1.2
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  spelling:
    image: spelling_server
    build: ./spelling
    ports:
      - "6543"
    volumes:
      - ./spelling/models:/opt/nmt-keras/models
      - ./spelling/config.py:/opt/nmt-keras/config.py
      - ./spelling/dataset:/opt/nmt-keras/dataset
      - ./spelling/config_online.py:/opt/nmt-keras/demo-web/config_online.py
    networks:
      net:
        ipv4_address: 172.28.1.3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
