version: '2.4'
services:
  web:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ./demo-web:/var/www/html
    networks:
      net:
        ipv4_address: 172.28.1.1
  modernization:
    image: modernization_server
    build: ./modernization
    ports:
      - "6542"
    volumes:
      - ./modernization/model:/opt/nmt-keras/model
      #- ./modernization/joint_bpe:/home/lvapeab/DATASETS/demo-web/esen/joint_bpe/
      - ./modernization/model/config.py:/opt/nmt-keras/config.py
    networks:
      net:
        ipv4_address: 172.28.1.2
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  spelling:
    image: spelling_server
    build: ./spelling
    ports:
      - "6543"
    volumes:
      - ./spelling/model:/opt/nmt-keras/model
      #- ./spelling/joint_bpe:/home/lvapeab/DATASETS/demo-web/esen/joint_bpe/
      - ./spelling/model/config.py:/opt/nmt-keras/config.py
    networks:
      net:
        ipv4_address: 172.28.1.3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
